-- 1. ASEGURAR COLUMNAS EN INSUMOS
ALTER TABLE insumos ADD COLUMN IF NOT EXISTS min INTEGER DEFAULT 0;
ALTER TABLE insumos ADD COLUMN IF NOT EXISTS casa INTEGER DEFAULT 0;
ALTER TABLE insumos ADD COLUMN IF NOT EXISTS mora INTEGER DEFAULT 0;
ALTER TABLE insumos ADD COLUMN IF NOT EXISTS deposito INTEGER DEFAULT 0;
ALTER TABLE insumos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. ASEGURAR COLUMNAS EN PEDIDOS
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS titulo TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS proveedor TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS categoria TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'Iniciado';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS receta_url TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS formulario_url TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. ASEGURAR COLUMNAS EN ANALISIS
ALTER TABLE analisis ADD COLUMN IF NOT EXISTS nombre TEXT;
ALTER TABLE analisis ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
ALTER TABLE analisis ADD COLUMN IF NOT EXISTS archivo_url TEXT;
ALTER TABLE analisis ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 4. ASEGURAR COLUMNAS EN TURNOS
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS profesional TEXT;
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS fecha DATE;
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS hora TEXT;
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS lugar TEXT;
ALTER TABLE turnos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 5. TABLA MÉDICOS (EQUIPO)
CREATE TABLE IF NOT EXISTS medicos (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT,
    especialidad TEXT,
    telefono TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. POLICIES (ASEGURAR ACCESO TOTAL)
ALTER TABLE insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE analisis ENABLE ROW LEVEL SECURITY;
ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "todo_insumos" ON insumos;
CREATE POLICY "todo_insumos" ON insumos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "todo_pedidos" ON pedidos;
CREATE POLICY "todo_pedidos" ON pedidos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "todo_analisis" ON analisis;
CREATE POLICY "todo_analisis" ON analisis FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "todo_turnos" ON turnos;
CREATE POLICY "todo_turnos" ON turnos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "todo_medicos" ON medicos;
CREATE POLICY "todo_medicos" ON medicos FOR ALL USING (true) WITH CHECK (true);
