-- TABLA DE COMPRAS Y REINTEGROS
CREATE TABLE IF NOT EXISTS public.compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    insumo TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    factura_url TEXT,
    estado TEXT DEFAULT 'pendiente' -- pendiente, reintegro_pedido
);

-- Habilitar RLS
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso para anon (simplificado para el entorno del usuario)
CREATE POLICY "Acceso total compras" ON public.compras FOR ALL USING (true) WITH CHECK (true);

-- Agregar columna 'formulario_url' a pedidos si no existe
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pedidos' AND COLUMN_NAME = 'formulario_url') THEN
        ALTER TABLE public.pedidos ADD COLUMN formulario_url TEXT;
    END IF;
END $$;
